name: vwave
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  firebase_core: ^3.3.0
  pinput: ^3.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  google_fonts: ^6.2.1
  device_preview: ^1.1.0
  firebase_auth: ^5.1.4
  #  firebase_ui_auth: ^1.8.0
  #  firebase_ui_oauth_google: ^1.2.11
  #  firebase_ui_oauth_apple: ^1.2.11
#  flutter_facebook_auth: ^6.0.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  flutter_riverpod: ^2.4.9
  firebase_dynamic_links: ^6.0.3
  firebase_database: ^11.0.4
  firebase_analytics: ^11.2.1
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.0.4
  firebase_remote_config: ^5.0.4
  firebase_app_check: ^0.3.0+4
  firebase_crashlytics: ^4.0.4
  flutter_image_compress: ^2.3.0
  image_cropper: ^5.0.1
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  flutter_timezone: ^1.0.8
  device_info_plus: ^10.1.0
  truncate: ^3.0.1
  rxdart: ^0.28.0
  file_picker: ^8.0.6
  #  extended_image: ^8.1.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  timezone: ^0.9.4
  cloud_firestore: ^5.2.1
  firebase_ui_firestore: ^1.6.4
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  modal_progress_hud_nsn: ^0.5.1
  readmore: ^2.2.0
  path_provider: ^2.1.2
  share_plus: ^9.0.0
  #  image_downloader: ^0.31.0
  google_places_flutter: ^2.0.7
  url_launcher: ^6.3.0
  flutter_widget_from_html: ^0.15.1
  dash_chat_2: ^0.0.21
  flutter_local_notifications: ^17.2.1+1 #^16.3.0
  webview_flutter: ^4.4.4
  get: ^4.6.6
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.5.3
  google_maps_flutter_android: ^2.6.2
  geolocator: ^10.1.0
  location: ^5.0.0
  geoflutterfire_plus: ^0.0.26 #^0.0.20
  intl_phone_field2: ^3.3.4
  agora_rtc_engine: ^6.3.2
#  flutter_screen_recording: ^2.0.10
  dio: ^5.4.3+1
  pretty_qr_code: ^3.3.0
  maps_launcher: ^2.2.1
#  flutter_instagram_stories: ^1.0.3+3
#  flutter_story_editor: ^0.0.2
  flutter_video_info: ^1.3.2
  video_thumbnail: ^0.5.3
#  chewie: ^1.8.1
  video_player: ^2.9.1
  media_info: ^0.12.0+2
  camera: ^0.11.0+1
#  video_compress: ^3.1.0
  circle_progress_bar: ^0.1.2
#  cached_video_player_plus: ^2.0.0 #remember to upgrade
  flutter_cache_manager: ^3.3.2
  flutter_cache_manager_firebase: ^2.0.2
  get_storage: ^2.0.0
#  flutter_isolate: ^2.0.4
#  isolate_handler: ^1.0.2
  share_screenshot_widget: ^0.0.5
#  flutter_animated_progress: ^1.2.1
  showcaseview: ^3.0.0
  keep_screen_on: ^3.0.0
  add_2_calendar: ^3.0.1
#  hive: ^2.2.3
#  hive_flutter: ^1.1.0
#  flutter_firebase_chat_core: ^1.6.8
#  open_filex: ^4.4.0
#  flutter_chat_ui: ^1.6.14
#  miroru_story_editor: ^1.1.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
#  hive_generator: ^2.0.1

dependency_overrides:
  firebase_storage: ^12.1.1
  rxdart: ^0.28.0
#  file_picker: ^6.1.1
#  device_info_plus: ^9.1.1
#  intl: ^0.18.1
  share_plus: ^9.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
#    - assets/icons/notifications/
    - assets/images/
    - assets/svg/
    - assets/svg/navigation/
#    - assets/svg/home/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
