// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4oNGM5t0eDpb1DgTlG_nOT7v3NguoiCE',
    appId: '1:712794258578:android:0d7266ae5d44f54707fa4b',
    messagingSenderId: '712794258578',
    projectId: 'getvwaveapp',
    databaseURL: 'https://getvwaveapp-default-rtdb.firebaseio.com',
    storageBucket: 'getvwaveapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3-meHHBZ5XevwtN68r3UobCvNs3kRhCE',
    appId: '1:712794258578:ios:7b50d0010801823707fa4b',
    messagingSenderId: '712794258578',
    projectId: 'getvwaveapp',
    databaseURL: 'https://getvwaveapp-default-rtdb.firebaseio.com',
    storageBucket: 'getvwaveapp.appspot.com',
    iosClientId: '712794258578-69ddmdl6d9tef3u4kptg15ivtldsnmt1.apps.googleusercontent.com',
    iosBundleId: 'com.vwave.app.vwave',
  );
}
